---
title: "Untitled"
output: html_document
---

```{r}
library(readxl)
Tasa <- read_excel("C:/Users/user/Documents/Jill/Universidad/Noveno semestre/Econometria Financiera/Tasa.xlsx")
View(Tasa)
attach(Tasa)
Tasa <- Desempleo_des




y<-ts(`DTF`,frequency = 12, start=c(1986,01))
fechas=seq(as.Date("1986/1/1"), length.out = length(y), by="months")

```


```{r}
install.packages("TSA")
install.packages("tseries")
install.packages("corrgram")
install.packages("forecast")
install.packages("fgarch")
install.packages("timeDate")
install.packages("timeSeries")
install.packages("fBasics")
install.packages("lmtest")

library(TSA)
library(tseries)
library(corrgram)
library(forecast)
library(fGarch)
library(timeDate)
library(timeSeries)
library(fBasics)
library(lmtest)
```

## Including Plots

```{r}
#Gráfica de la serie
ts.plot(`y`, main="Tasa DTF")

#Transformar la serie
diferencia<-diff(y)
# la variacion porcentual se calcula de manera discreta
variacion<-diff(y)/lag(y,-1)
#transformación para retornos se calculan de manera continua
retorno<-diff(log(y))
ts.plot(`diferencia`, main="Diferencia")
ts.plot(`variacion`, main="Variación porcentual")
ts.plot(`retorno`, main="Retorno")

```


```{r}
#Prueba de estacionariedad
adf.test(y)
adf.test(diferencia)
adf.test(variacion)
adf.test(retorno)

```


```{r}
#Funciones de autocorrelación
par(mfrow=c(3,2))
acf(y,lag.max = 36)
pacf(y,lag.max = 36)
acf(diferencia,lag.max = 36)
pacf(diferencia,lag.max = 36)
acf(variacion,lag.max = 36)
pacf(variacion,lag.max = 36)
par(mfrow=c(1,2))
acf(retorno,lag.max = 36)
pacf(retorno,lag.max = 36)
#en este modelo no elijo uno a uno los rezagos sino que 
```


```{r}
#Estimar el modelo inicial
modelo<-arma(variacion,include.intercept = TRUE,lag=list(ar=c(1,3,8,11,25),
              ma=c(1,2,3,4,14,17,18,19,20,21,22,23,25,34)))
summary(modelo)

modelo<-arma(variacion,include.intercept = FALSE,lag=list(ar=c(3,8,11),
              ma=c(1,2)))
summary(modelo)

modelo<-arma(variacion,include.intercept = FALSE,lag=list(ar=c(1,3)))
summary(modelo)

modelo<-arma(variacion,order=c(1,4))
summary(modelo)

auto.arima(y)
auto.arima(variacion)

modelo<-arima(variacion, c(3,0,4))
summary(modelo)
coeftest(modelo)
```


```{r}
##Generar variable dummy
a<-matrix(0,nrow=179,ncol=1)
b<-matrix(1,nrow=231,ncol=1)
d1<-rbind(a,b)

mod_dummy<-arimax(variacion,order=c(1,0,4), xreg=d1)
mod_dummy

```

```{r}
#Generar los residuales del modelo ajustado
error<-residuals(modelo)
e1<-error[!is.na(error)]

```


```{r}
### Normalidad
par(mfrow=c(1,2))
qqnorm(scale(e1))
qqline(scale(e1),col="blue")

histograma<-function(modelo, nbreaks=12) {
  hist(e1, breaks=nbreaks, freq=FALSE, main="Histograma de residuales")
  rug(jitter(e1), col="red")
  curve(dnorm(x,mean=mean(e1), sd=sd(e1)), add=TRUE, col="blue", lwd=2)
  lines(density(e1)$x, density(e1)$y, col="yellow", lwd=2, lty=2)
}
par(mfrow=c(1,1))
histograma(modelo)

jarque.bera.test(e1)
ks.test(e1,"pnorm")

```


```{r}
### No autocorrelación
plot(scale(e1),type="l",main="Residuales")
par(mfrow=c(1,2))
acf(e1)
pacf(e1)

acf_e1 <- acf(e1, plot=FALSE, lag.max=36)$acf
pacf_e1 <- pacf(e1, plot=FALSE, lag.max=36)$acf

Q_stats <- c()
Q_pvals <- c()
for (i in 1:36) {
  Q = Box.test(e1, lag=i)
  Q_stats[[i]] <- Q$statistic
  Q_pvals[[i]] <- Q$p.value
}
corrgram <- cbind(LAG=seq(1,36), ACF=acf_e1, PACF=pacf_e1, Q=Q_stats, "Prob>Q"=Q_pvals)
corrgram

```


```{r}
###Homocedasticidad
e1_cuad=(e1-mean(e1))^2

par(mfrow=c(1,2))
acf(e1_cuad)
pacf(e1_cuad)

acf_e1c <- acf(e1_cuad, plot=FALSE, lag.max=12)$acf
pacf_e1c <- pacf(e1_cuad, plot=FALSE, lag.max=12)$acf

Q_stats <- c()
Q_pvals <- c()
for (i in 1:12) {
  Q = Box.test(e1_cuad, lag=i)
  Q_stats[[i]] <- Q$statistic
  Q_pvals[[i]] <- Q$p.value
}
corrgram <- cbind(LAG=seq(1,12), ACF=acf_e1c, PACF=pacf_e1c, Q=Q_stats, "Prob>Q"=Q_pvals)
corrgram

```


```{r}
##Pronóstico
predict(mod_dummy, n.ahead=3, newxreg=c(1,1,1))
```


```{r}
###Estimar modelo de heterocedasticidad condicionada
#usa distribucion normal
# la funcion garch fit requiere especificar el modelo de ecuacion de la #media que debe ser un arma el componente garch, la variable sobre la que #estoy generando el analisis o la transformacion que estoy utilizando
m1=garchFit(~arma(1,4)+garch(1,1),data=variacion,trace=FALSE,cond.dist = c("norm")) 
summary(m1)
#usa distribucion t student
m2=garchFit(~arma(1,2)+garch(1,1),data=retorno,trace=FALSE,cond.dist = c("std")) 
summary(m2)
#usa distribucion ged
m3=garchFit(~arma(1,2)+garch(1,1),data=retorno,trace=FALSE,cond.dist = c("ged")) 
summary(m3)

```


```{r}
##Ajuste errores
#comparacion de errores con la distribucion t student
error2<-residuals(m3)
#la comparo con una distribución t
ks.test(error2,"pt",(df=406))

mean(e3)
sd(e3)
#comparacion de errores con la distribucion GED
gedFit(e3)
x<-rged(225,mean=4.13962,sd=67.8701,nu=1.43156)

par(mfrow=c(1,1))
hist(e3, n = 12, probability = TRUE, border = "white", col = "steelblue")
box()
x = seq(min(e3), max(e3), length = 224)
lines(x, dsged(x), lwd = 2)

par(mfrow=c(1,1))
hist(e2, n = 12, probability = TRUE, border = "white", col = "steelblue")
box()
lines(x, lwd = 2)

hist(e3, breaks=12, freq=FALSE, main="Histograma de residuales")
rug(jitter(e3), col="red")
curve(dged(x,mean=mean(e3), sd=sd(e3),nu=1.43156), add=TRUE, col="blue", lwd=2)
lines(density(e3)$x, density(e3)$y, col="yellow", lwd=2, lty=2)

```


